[placeholders]
licence = { prompt = "Licence", choices = ["GPL3", "MIT"], default = "GPL3", type = "string" }
organization = { prompt = "Copyright holder", default = "EnergoStalin", type = "string" }

[hooks]
pre = ["hooks/year.rhai", "hooks/licence.rhai"]

[template]
cargo_generate_version = ">=0.23.7"
include = [
  "src/lib.rs",
  "Cargo.toml",
  "rustfmt.toml",
  ".editorconfig",
  "LICENCE.txt",
  ".gitignore"
]
ignore = ["hooks", "licences"]

[conditional.'crate_type != "lib"']
include = ["src/main.rs"]
