[template]
cargo_generate_version = ">=0.23.7"
include = ["*"]
ignore = ["hooks", "licences"]

[conditional.'within_cargo_project != true'.placeholders]
licence = { prompt = "Licence", choices = ["GPL3", "MIT"], default = "GPL3", type = "string" }
organization = { prompt = "Copyright holder", default = "EnergoStalin", type = "string" }

[conditional.'within_cargo_project == true']
ignore = [
  "rustfmt.toml",
  ".editorconfig",
  "LICENCE.txt",
  ".gitignore"
]

[conditional.'within_cargo_project != true'.hooks]
pre = ["hooks/year.rhai", "hooks/licence.rhai"]

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs"]

[conditional.'crate_type != "lib"']
ignore = ["src/lib.rs"]
